name: NIGHTLY
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'
jobs:
  Build_nightly:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          files:
          - "camunda-modeler-nightly-linux-x64.tar.gz"
        - os: macos-11
          files:
          - "camunda-modeler-nightly-mac.dmg"
          - "camunda-modeler-nightly-mac.zip"
        - os: windows-2019
          files:
          - "camunda-modeler-nightly-win-ia32.zip"
          - "camunda-modeler-nightly-win-x64.zip"
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Build nightly (Linux)
      if: ${{ runner.os == 'Linux' }}
      env:
        CSC_LINK: "${{ secrets.CSC_LINK }}"
        CSC_KEY_PASSWORD: "${{ secrets.CSC_KEY_PASSWORD }}"
        ET_ENDPOINT: "${{ secrets.ET_ENDPOINT }}"
        MIXPANEL_TOKEN: "${{ secrets.MIXPANEL_PROJECT_TOKEN }}"
        MIXPANEL_STAGE: "int"
        SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
        SENTRY_DSN: "${{ secrets.SENTRY_DSN }}"
        SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
        SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
        UPDATES_SERVER_PRODUCT_NAME: "${{ secrets.UPDATES_SERVER_PRODUCT_NAME }}"
      run: npm run build -- --linux --nightly

    - name: Build nightly (MacOS)
      if: ${{ runner.os == 'macOS' }}
      env:
        APPLE_DEVELOPER_ID: "${{ secrets.APPLE_DEVELOPER_ID }}"
        APPLE_DEVELOPER_ID_PASSWORD: "${{ secrets.APPLE_DEVELOPER_ID_PASSWORD }}"
        CSC_LINK: "${{ secrets.CSC_LINK }}"
        CSC_KEY_PASSWORD: "${{ secrets.CSC_KEY_PASSWORD }}"
        ET_ENDPOINT: "${{ secrets.ET_ENDPOINT }}"
        MIXPANEL_TOKEN: "${{ secrets.MIXPANEL_PROJECT_TOKEN }}"
        MIXPANEL_STAGE: "int"
        SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
        SENTRY_DSN: "${{ secrets.SENTRY_DSN }}"
        SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
        SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
        UPDATES_SERVER_PRODUCT_NAME: "${{ secrets.UPDATES_SERVER_PRODUCT_NAME }}"
      run: npm run build -- --mac --nightly

    - name: Build nightly (Windows)
      if: ${{ runner.os == 'Windows' }}
      env:
        CSC_LINK: "${{ secrets.WIN_CSC_LINK }}"
        CSC_KEY_PASSWORD: "${{ secrets.WIN_CSC_KEY_PASSWORD }}"
        ET_ENDPOINT: "${{ secrets.ET_ENDPOINT }}"
        MIXPANEL_TOKEN: "${{ secrets.MIXPANEL_PROJECT_TOKEN }}"
        MIXPANEL_STAGE: "int"
        SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
        SENTRY_DSN: "${{ secrets.SENTRY_DSN }}"
        SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
        SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
        UPDATES_SERVER_PRODUCT_NAME: "${{ secrets.UPDATES_SERVER_PRODUCT_NAME }}"
      run: npm run build -- --win --nightly

    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.4.3
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        exportEnv: false
        secrets: |
          secret/data/common/jenkins/downloads-camunda-cloud_google_sa_key DOWNLOAD_CENTER_GCLOUD_KEY_BYTES | GCP_CREDENTIALS_NAME;
    - name: Upload artifact to Camunda Download Center (part 1)
      uses: camunda/download-center-upload-action@v0.1.0
      with:
        gcp_credentials: ${{ steps.secrets.outputs.GCP_CREDENTIALS_NAME }}
        env: 'dev'
        artifact_subpath: 'nightly'
        artifact_file: 'dist/${{ matrix.files[0] }}'
    - name: Upload artifact to Camunda Download Center (part 2)
      if: '${{ matrix.files[1] }}' != ''
      uses: camunda/download-center-upload-action@v0.1.0
      with:
        gcp_credentials: ${{ steps.secrets.outputs.GCP_CREDENTIALS_NAME }}
        env: 'dev'
        artifact_subpath: 'nightly'
        artifact_file: 'dist/${{ matrix.files[1] }}'

  Post-Failure:
    needs: Build_nightly
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      uses: slackapi/slack-github-action@v1.15.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        slack-message: "Nightly build failed. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to the build.>"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
